<?php

/**
 * The ECR response model
 *
 * @author    Payrexx Development <info@payrexx.com>
 * @copyright Payrexx AG
 * @since     v1.0.0
 */

namespace Payrexx\Models\Response;

/**
 * Ecr response class
 *
 * @package \Payrexx\Models\Response
 */
class Ecr extends \Payrexx\Models\Request\Ecr
{
    /**
     * The authentication token generated by the pairing process.
     * Use this token for subsequent ECR operations.
     */
    protected string $token;

    /**
     * The status of the pairing (e.g., 'confirmed', 'pending').
     */
    protected string $status;

    /**
     * Optional: If the backend returns the terminal configuration or ID
     */
    protected string $terminalId;

    public function setToken(string $token): void
    {
        $this->token = $token;
    }

    public function getToken(): string
    {
        return $this->token;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setTerminalId(string $terminalId): void
    {
        $this->terminalId = $terminalId;
    }

    public function getTerminalId(): string
    {
        return $this->terminalId;
    }
}